server:
  port: 9090


# $2a$10$/TerzefJ6d1wLymtBiNM3e9fnZLtGlqNcoQVL24SJiW.H528.odfC
# 123456
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root