server:
  port: 9090

spring:


  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: mp-t

  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
