server:
  port: 9090
spring:
  activemq:
    broker-url: tcp://139.196.166.75:61617
    in-memory: false
    pool:
      # 最大链接数
      max-connections: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8

