server:
  port: 9090


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 10
      max-wait: 10000


  thymeleaf:
    cache: false

#  redis:
#    password:
#    host:


#debug: true
