server:
  port: 9090
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置druid
    initial-size: 5
    max-active: 20
