server:
  port: 8090

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/quartz?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      max-lifetime: 1800000
      idle-timeout: 120000
      maximum-pool-size: 30
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
#  quartz:
#    scheduler-name: QuartScheduler
quartz:
  scheduler:
    instanceName: QuartScheduler
