server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    password: 123456
    username: root
  data:
    mongodb:
      host: 47.96.230.44
      port: 27017
      database: webflux

